# Generated by Django 3.2.9 on 2021-11-14 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pract2_products1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'allergy_drinks',
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='desciption',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='allergy',
            table='allergies',
        ),
        migrations.DeleteModel(
            name='allergy_drink',
        ),
        migrations.AddField(
            model_name='allergydrink',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pract2_products1.allergy'),
        ),
        migrations.AddField(
            model_name='allergydrink',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pract2_products1.drink'),
        ),
    ]
