# Generated by Django 3.2.9 on 2021-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract2_products1', '0003_auto_20211114_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='desciption',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='drink',
            name='english_name',
            field=models.CharField(blank=True, default=' ', max_length=45),
        ),
    ]
