# Generated by Django 3.2.9 on 2021-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract2_products1', '0004_auto_20211114_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
